// <auto-generated />
namespace University.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Inheritance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inheritance));
        
        string IMigrationMetadata.Id
        {
            get { return "201310111815427_Inheritance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
