// <auto-generated />
namespace University.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TutorialChapter4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TutorialChapter4));
        
        string IMigrationMetadata.Id
        {
            get { return "201310062000548_TutorialChapter4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
